version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    command: node server.js
    ports:
      - 7777:7777
  tests:
    build: 
      context: ./testes
      dockerfile: dockerfile
    network_mode: host
    image: robot
    shm_size: "256M"
    environment:
      USERNAME: Justus
    volumes: [
      "$PWD/suites:/suites",
      "$PWD/scripts:/scripts",
      "$PWD/reports:/reports"
    ]